apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: F:\Credit — kopia\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: postgresql
  name: postgresql
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgresql
  type: LoadBalancer
