apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: F:\Credit — kopia\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: springboot-customer
  name: springboot-customer
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8080
  selector:
    io.kompose.service: springboot-customer
  type: LoadBalancer
