apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: F:\Credit — kopia\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: springboot-credit
  name: springboot-credit
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: springboot-credit
  type: LoadBalancer
