apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: F:\Credit — kopia\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  labels:
    io.kompose.service: springboot-product
  name: springboot-product
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: springboot-product
    strategy:
  minReadySeconds: 5
  template:
    metadata:
      annotations:
        kompose.cmd: F:\Credit — kopia\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      labels:
        io.kompose.service: springboot-product
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: create
          image: product:1
          name: springboot-product
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1Gi
              cpu: "2"
            requests:
              memory: 256Mi
              cpu: "0.2"
      restartPolicy: Always
status: {}
