FROM maven:3.8.4-openjdk-17-slim AS build
RUN mkdir /project
COPY . /project
WORKDIR /project
RUN mvn install -DskipTests

FROM openjdk:17-slim-buster@sha256:c5a264f4adb92b19961b4d79f9ac2b5df3ce8932413688851cd221b7939a0736
RUN mkdir /app
RUN addgroup --system javauser && useradd --create-home --shell /bin/bash javauser -g javauser
COPY --from=build /project/target/product-0.0.1-SNAPSHOT.jar /app/java-application.jar
WORKDIR /app
RUN chown -R javauser:javauser /app
USER javauser
CMD  "java" "-jar" "java-application.jar"